# Generated by Django 4.2 on 2023-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_alter_mapelementmodel_name_alter_maplayermodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapelementmodel",
            name="metadata",
            field=models.JSONField(default=None),
        ),
    ]
