# Generated by Django 4.2 on 2023-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_mapelementmodel_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapelementmodel",
            name="metadata",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
